import os
import sys
import copy
import json
import random
import datetime
from collections import deque
import logging

import torch
import torch.nn as nn
import torch.optim as optim
import fire

# Ensure we can import from the main project root
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from examples.ToT.blocksworld.tot_inference import BWConfig, BlocksWorldModel, BWState
from reasoners.benchmark.blocksworld import BWEvaluator
import reasoners.benchmark.bw_utils as bw_utils


# ==========================================
# 1. ENVIRONMENT WRAPPER
# ==========================================
class BWThoughtEnv:
    """
    Wraps the ToT BlocksWorld components (world_model, config, evaluator) into a standard 
    RL-style environment. Instead of tokens, a single "step" corresponds to a full text
    "thought" (an action generated by the LLM).
    """
    def __init__(self, world_model: BlocksWorldModel, config: BWConfig, evaluator: BWEvaluator, use_cache: bool = True):
        self.world_model = world_model
        self.config = config
        self.evaluator = evaluator
        
        # --- Caching System ---
        self.use_cache = use_cache
        # thought_cache maps a unique state signature to a list of possible thought strings proposed by the LLM
        self.thought_cache = {} 
        
        # --- Dynamic Text Tokenizer ---
        # Since thoughts are physical words, we build a lightweight dynamic dictionary mapping words to IDs
        # so we can pass integer tensors into our Heuristic Neural Network.
        self.word2idx = {"<PAD>": 0, "<UNK>": 1}
        self.idx2word = {0: "<PAD>", 1: "<UNK>"}
        
        self.current_instance = None # Holds the active training problem
        self.current_prompt = None

    def reset(self, instance: dict):
        """Resets the environment to a specific BlocksWorld training problem."""
        self.current_instance = instance
        
        # 1. Ask the evaluator to randomly sample few-shot examples and build the complex prompt template
        self.current_prompt = self.evaluator.sample_prompt(shuffle_prompt=True, num_shot=4)
        
        # 2. Bind the active problem and the prompt framework to the action-generator (config)
        self.config.update_example(instance, prompt=self.current_prompt)
        
        # 3. Update our Neural Network vocabulary with words from the initial and goal states
        self._update_vocab(instance["init"])
        self._update_vocab(instance["goal"])
        
        # 4. Return the starting state (Step 0, clean action history)
        return self.world_model.init_state()

    def get_actions_cached(self, state: BWState):
        """Retrieves proposed thoughts from the LLM, securely checking the local Cache first."""
        if not self.use_cache:
            return self.config.get_actions(state)
            
        # The key is a string representation of the steps taken so far
        state_key = str(state.action_history)
        
        if state_key not in self.thought_cache:
            # Query the LLM (Very Expensive operation)
            actions = self.config.get_actions(state)
            self.thought_cache[state_key] = actions
            
            # Immediately add any new words from the LLM's thoughts to our tokenizer dictionary
            for act in actions:
                self._update_vocab(act)
                
        return self.thought_cache[state_key]

    def _update_vocab(self, text: str):
        """Helper to break a text sequence into words and map them to unqiue integer IDs."""
        words = text.replace('\n', ' ').split()
        for w in words:
            if w not in self.word2idx:
                idx = len(self.word2idx)
                self.word2idx[w] = idx
                self.idx2word[idx] = w

    def is_goal(self, state: BWState) -> bool:
        """
        Uses the internal validation script to determine mathematically if the block placements
        satisfy the goal requirements for the current problem dataset.
        """
        if len(state.action_history) == 0:
            return False
            
        output_plan = "\n".join(state.action_history) + "\n"
        # BWEvaluator returns True if the output_plan legitimately solves the current instance
        correct = self.evaluator.eval_output(self.current_instance, output_plan)
        return correct

    def is_terminal(self, state: BWState) -> bool:
        """A state is a dead-end if we reached the step limit or already solved the problem."""
        return self.world_model.is_terminal(state) or self.is_goal(state)

    def expand(self, state: BWState) -> list:
        """Returns a list of tuples (next_state, step_cost) for all possible thoughts from the LLM."""
        actions = self.get_actions_cached(state)
        results = []
        for action in actions:
            next_state, _ = self.world_model.step(state, action)
            results.append((next_state, 1.0)) # Every thought executed costs 1 step
        return results

    def state_to_tensor(self, state: BWState, max_len: int = 150) -> torch.Tensor:
        """
        Converts a text state into integers for the PyTorch heuristic network.
        We concatenate [Init State] + [Goal State] + [Action 1] + [Action 2] ... 
        so the network knows exactly what problem it's solving AND its current progress.
        """
        text_parts = [self.current_instance["init"], self.current_instance["goal"]] + state.action_history
        full_text = " ".join(text_parts).replace('\n', ' ')
        words = full_text.split()
        
        # Translate words to IDs, capped at max_len
        ids = [self.word2idx.get(w, self.word2idx["<UNK>"]) for w in words][:max_len]
        
        # Pad sequence so all tensors have identical dims
        padded_ids = ids + [self.word2idx["<PAD>"]] * (max_len - len(ids))
        
        # Output shape: [1, max_len]
        return torch.tensor(padded_ids).unsqueeze(0)


# ==========================================
# 2. NEURAL NETWORK ARCHITECTURE
# ==========================================
class ThoughtHeurModel(nn.Module):
    """
    Predicts the Cost-to-Go (number of remaining thoughts to reach the goal).
    Replaces the standard A* heuristic function.
    """
    def __init__(self, vocab_size: int, embedding_dim=16, hidden_dim=64, max_len=150):
        super(ThoughtHeurModel, self).__init__()
        # Word Embeddings scale our dynamically created vocabulary IDs into rich floats
        self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim, padding_idx=0)
        
        # 1 Hidden layer. Input dim is fixed at max_seq_len * embedding_dim
        self.fc1 = nn.Linear(embedding_dim * max_len, hidden_dim)
        
        # Output layer gives a singular float value (The Predicted Distance)
        self.fc2 = nn.Linear(hidden_dim, 1)
        self.relu = nn.ReLU()

    def forward(self, x):
        # x is [Batch, Sequence_Len]
        embedded = self.embedding(x) # [Batch, Seq, Emb]
        
        # Flatten token embeddings into a single 1D vector per batch item
        flattened = embedded.view(embedded.size(0), -1) 
        
        out = self.relu(self.fc1(flattened))
        out = self.fc2(out)
        
        # Enforce that remaining distance cannot be negative using ReLU!
        return torch.relu(out)


# ==========================================
# 3. TRAINING LOOP
# ==========================================
class HeuristicTrainer:
    def __init__(self, env: BWThoughtEnv, model: ThoughtHeurModel, lr=1e-3):
        self.env = env
        self.model = model
        
        # The Target network stabilizes Q-Learning by preventing a feedback loop. 
        # It provides fixed target values.
        self.target_model = copy.deepcopy(model)
        self.target_model.eval()
        
        self.optimizer = optim.Adam(model.parameters(), lr=lr)
        self.criterion = nn.MSELoss()
        
        # Memory bank mapping transitions (State, is_solved, neighbors)
        self.replay_buffer = deque(maxlen=50000) 
        self.train_steps = 0

    def add_to_buffer(self, state: BWState):
        is_solved = self.env.is_goal(state)
        neighbors = self.env.expand(state)
        # We only save to memory if there are actually neighbors available
        if neighbors or is_solved: 
            self.replay_buffer.append((state, is_solved, neighbors))

    def update_target_network(self):
        """Syncs the stable target weights with the latest training weights."""
        self.target_model.load_state_dict(self.model.state_dict())

    def train_step(self, batch_size=32):
        if len(self.replay_buffer) < batch_size:
            return None
            
        # Sample mini-batch randomly
        batch = random.sample(self.replay_buffer, batch_size)
        states, is_solved_list, neighbors_batch = zip(*batch)
        
        # Assemble inputs from the batch
        inputs = torch.cat([self.env.state_to_tensor(s) for s in states])
        targets = []
        
        with torch.no_grad():
            for i, state in enumerate(states):
                if is_solved_list[i]:
                    targets.append(0.0) # Goal state has distance 0!
                elif self.env.is_terminal(state):
                    targets.append(10.0) # Hit the step limit / hit a dead-end
                else:
                    # Gather neighbor inputs
                    n_states = [n[0] for n in neighbors_batch[i]]
                    n_costs = [n[1] for n in neighbors_batch[i]]
                    
                    if len(n_states) == 0:
                        targets.append(10.0)
                        continue
                        
                    n_inputs = torch.cat([self.env.state_to_tensor(ns) for ns in n_states])
                    
                    # Q-Learning target = min(Cost_to_neighbor + Heuristic(neighbor))
                    n_values = self.target_model(n_inputs).squeeze(-1).tolist()
                    if isinstance(n_values, float):  # If only 1 neighbor, it returns float not list
                        n_values = [n_values]
                        
                    target_val = min([c + nv for c, nv in zip(n_costs, n_values)])
                    targets.append(target_val)
                    
        targets_tensor = torch.tensor(targets).unsqueeze(1).float()
        
        # Forward and MSE Backprop
        self.model.train()
        self.optimizer.zero_grad()
        predictions = self.model(inputs)
        loss = self.criterion(predictions, targets_tensor)
        loss.backward()
        self.optimizer.step()
        
        self.train_steps += 1
        return loss.item()


# ==========================================
# MAIN EXECUTION ROUTINE
# ==========================================
def main(
    base_lm: str = 'openai',
    model_dir: str = '',
    prompt_path: str = 'examples/CoT/blocksworld/prompts/pool_prompt_v1.json',
    data_path: str = 'examples/CoT/blocksworld/data/split_v1/split_v1_step_2_data.json',
    config_file: str = 'examples/CoT/blocksworld/data/bw_config.yaml',
    domain_file: str = 'examples/CoT/blocksworld/data/generated_domain.pddl',
    output_dir: str = 'logs/train_v_heur',
    batch_size: int = 16,
    n_candidate: int = 4,                   
    max_episodes: int = 20,                
    use_cache: bool = True,                 
    max_steps: int = 6,
    temperature: float = 0.8
):
    # ---------------------------------------------
    # SETUP LOGGING AND DIRS
    # ---------------------------------------------
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(output_dir, timestamp)
    os.makedirs(run_dir, exist_ok=True)
    
    print(f"Setting up training environment... Results will be saved to: {run_dir}")

    # ---------------------------------------------
    # LOAD PROMPT DICT
    # ---------------------------------------------
    with open(prompt_path) as f:
        prompt = json.load(f)

    # ---------------------------------------------
    # INITIALIZE LLM
    # ---------------------------------------------
    if base_lm == 'openai':
        from reasoners.lm import OpenAIModel
        # To match the logic in tot_inference.py
        model = OpenAIModel(model='gpt-3.5-turbo', temperature=temperature, max_tokens=2048)
    elif base_lm == 'exllama':
        from reasoners.lm import ExLlamaModel
        device = torch.device("cuda:0")
        model = ExLlamaModel(model_dir, lora_dir=None, device=device, 
                                max_batch_size=batch_size, max_new_tokens=200, 
                                max_seq_length=2048, log_output=False)
    else:
        raise NotImplementedError(f"Model {base_lm} not fully integrated into train_v_heur script yet.")

    # ---------------------------------------------
    # SETUP ToT BLOCKSWORLD INFRASTRUCTURE
    # ---------------------------------------------
    world_model = BlocksWorldModel(base_model=model, prompt=prompt, max_steps=max_steps)
    config = BWConfig(base_model=model, prompt=prompt, temperature=temperature, n_candidate=n_candidate)
    
    # We use DFS extractor here purely to satisfy the Evaluator object, but we overwrite output dynamically in is_goal anyway
    from examples.ToT.blocksworld.tot_inference import dfs_bw_extractor 
    evaluator = BWEvaluator(config_file=config_file, domain_file=domain_file, data_path=data_path, 
                            init_prompt=prompt, output_extractor=dfs_bw_extractor)

    # ---------------------------------------------
    # 80/20 DATASET SPLIT
    # ---------------------------------------------
    full_dataset = evaluator.full_dataset
    random.shuffle(full_dataset)
    split_idx = int(0.8 * len(full_dataset))
    train_data = full_dataset[:split_idx]
    test_data = full_dataset[split_idx:]
    
    # Save the splits so they can be reproduced!
    split_save_path = os.path.join(run_dir, "train_test_split.json")
    with open(split_save_path, "w") as f:
        json.dump({"train": train_data, "test": test_data}, f, indent=2)
    print(f"Loaded {len(train_data)} Train instances and {len(test_data)} Test instances.")

    # ---------------------------------------------
    # INITIALIZE RL ENVIRONMENT AND HEUR TRAINER
    # ---------------------------------------------
    env = BWThoughtEnv(world_model, config, evaluator, use_cache=use_cache)
    
    # Pre-build our environment vocabulary from all problems in the train test!
    # Because our network needs a fixed vocabulary at start, we inject all init/goal strings.
    for prob in train_data + test_data:
        env._update_vocab(prob["init"])
        env._update_vocab(prob["goal"])

    # Allocate Neural Net now that vocab size is firmly known
    heur_model = ThoughtHeurModel(vocab_size=len(env.word2idx), max_len=150)
    trainer = HeuristicTrainer(env, heur_model)

    print("Beginning RL Epsilon-Greedy Random Walk...")
    
    # ---------------------------------------------
    # TRAINING LOOP
    # ---------------------------------------------
    for ep in range(max_episodes):
        # 1. Epsilon decay (more random at start, greedier at end)
        epsilon = max(0.1, 1.0 - (ep / (max_episodes * 0.5)))
        
        # 2. Pick a random problem instance to practice solving
        instance = random.choice(train_data)
        state = env.reset(instance)
        
        while True:
            # Replay buffer observation happens BEFORE taking an action
            trainer.add_to_buffer(state)
            
            if env.is_terminal(state):
                break
                
            # EXPLORATION: Explore a random LLM thought
            if random.random() < epsilon:
                actions = env.get_actions_cached(state)
                if not actions:
                    break
                # choose random thought!
                action = random.choice(actions) 
                
            # EXPLOITATION: Ask heuristic which LLM thought yields the lowest remaining distance
            else:
                neighbors = env.expand(state)
                n_states = [n[0] for n in neighbors]
                
                # If no thoughts available, we terminate the walk
                if len(n_states) == 0:
                    break
                    
                # Format thoughts for Neural Network Evaluation
                n_inputs = torch.cat([env.state_to_tensor(ns) for ns in n_states])
                
                with torch.no_grad():
                    n_values = trainer.target_model(n_inputs).squeeze(-1).tolist()
                    if isinstance(n_values, float): n_values = [n_values]
                
                # Pick thought with MINIMUM predicted cost
                best_idx = n_values.index(min(n_values))
                # Expand neighbor 0 element is state, from that we extract the *last action* to execute
                action = n_states[best_idx].action_history[-1] 
            
            # Formally take the step
            state, _ = env.world_model.step(state, action)
            
        # Update Target network weights conservatively
        if trainer.train_steps % 50 == 0:
            trainer.update_target_network()

        # Step the gradients!
        loss = trainer.train_step(batch_size=batch_size)
        
        if ep % 2 == 0:
            print(f"Episode {ep:03d} | Loss: {loss if loss else 0.0:.4f} | Epsilon: {epsilon:.2f} | Local Vocab: {len(env.word2idx)} words")

    print(f"\nTraining Complete! Saving final Model Weights to {run_dir}/heur_model.pth")
    torch.save(heur_model.state_dict(), os.path.join(run_dir, "heur_model.pth"))
    
    # Save the dictionary so future usages know how to map words -> IDs
    with open(os.path.join(run_dir, "vocab.json"), "w") as f:
        json.dump(env.word2idx, f, indent=2)
        

if __name__ == '__main__':
    fire.Fire(main)
