import os
import sys
import copy
import json
import random
import datetime
from collections import deque
import logging
import contextlib

import torch
import torch.nn as nn
import torch.optim as optim
import fire
from peft import get_peft_model, LoraConfig, TaskType

# Ensure we can import from the main project root
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from examples.ToT.blocksworld.tot_inference import BWConfig, BlocksWorldModel, BWState
from reasoners.benchmark.blocksworld import BWEvaluator
import reasoners.benchmark.bw_utils as bw_utils


# ==========================================
# 1. ENVIRONMENT WRAPPER
# ==========================================
class BWThoughtEnv:
    """
    Wraps the ToT BlocksWorld components (world_model, config, evaluator) into a standard 
    RL-style environment. Instead of tokens, a single "step" corresponds to a full text
    "thought" (an action generated by the LLM).
    """
    def __init__(self, world_model: BlocksWorldModel, config: BWConfig, evaluator: BWEvaluator, use_cache: bool = True):
        self.world_model = world_model
        self.config = config
        self.evaluator = evaluator
        
        # --- Caching System ---
        self.use_cache = use_cache
        # thought_cache maps a unique state signature to a list of possible thought strings proposed by the LLM
        self.thought_cache = {} 
        
        # --- Dynamic Text Tokenizer ---
        # Since thoughts are physical words, we build a lightweight dynamic dictionary mapping words to IDs
        # so we can pass integer tensors into our Heuristic Neural Network.
        self.word2idx = {"<PAD>": 0, "<UNK>": 1}
        self.idx2word = {0: "<PAD>", 1: "<UNK>"}
        
        self.current_instance = None # Holds the active training problem
        self.current_prompt = None

    def reset(self, instance: dict):
        """Resets the environment to a specific BlocksWorld training problem."""
        self.current_instance = instance
        
        # 1. Ask the evaluator to randomly sample few-shot examples and build the complex prompt template
        self.current_prompt = self.evaluator.sample_prompt(shuffle_prompt=True, num_shot=4)
        
        # 2. Bind the active problem and the prompt framework to the action-generator (config)
        self.config.update_example(instance, prompt=self.current_prompt)
        
        # 3. Update our Neural Network vocabulary with words from the initial and goal states
        self._update_vocab(instance["init"])
        self._update_vocab(instance["goal"])
        
        # 4. Return the starting state (Step 0, clean action history)
        return self.world_model.init_state()

    def get_actions_cached(self, state: BWState):
        """Retrieves proposed thoughts from the LLM, securely checking the local Cache first."""
        if not self.use_cache:
            return self.config.get_actions(state)
            
        # The key is a string representation of the steps taken so far
        state_key = str(state.action_history)
        
        if state_key not in self.thought_cache:
            # Query the LLM (Very Expensive operation)
            actions = self.config.get_actions(state)
            self.thought_cache[state_key] = actions
            
            # Immediately add any new words from the LLM's thoughts to our tokenizer dictionary
            for act in actions:
                self._update_vocab(act)
                
        return self.thought_cache[state_key]

    def _update_vocab(self, text: str):
        """Helper to break a text sequence into words and map them to unqiue integer IDs."""
        words = text.replace('\n', ' ').split()
        for w in words:
            if w not in self.word2idx:
                idx = len(self.word2idx)
                self.word2idx[w] = idx
                self.idx2word[idx] = w

    def is_goal(self, state: BWState) -> bool:
        """
        Uses the internal validation script to determine mathematically if the block placements
        satisfy the goal requirements for the current problem dataset.
        """
        if len(state.action_history) == 0:
            return False
            
        output_plan = "\n".join(state.action_history) + "\n"
        # BWEvaluator returns True if the output_plan legitimately solves the current instance
        # Suppress the incredibly messy C++ prints so it doesn't spam your terminal!
        with open(os.devnull, 'w') as f, contextlib.redirect_stdout(f):
            correct = self.evaluator.eval_output(self.current_instance, output_plan)
        return correct

    def is_terminal(self, state: BWState) -> bool:
        """A state is a dead-end if we reached the step limit or already solved the problem."""
        return self.world_model.is_terminal(state) or self.is_goal(state)

    def expand(self, state: BWState) -> list:
        """Returns a list of tuples (next_state, step_cost) for all possible thoughts from the LLM."""
        actions = self.get_actions_cached(state)
        results = []
        for action in actions:
            next_state, _ = self.world_model.step(state, action)
            results.append((next_state, 1.0)) # Every thought executed costs 1 step
        return results

    def state_to_text(self, state: BWState) -> str:
        """
        Converts a state into raw text for the LLM tokenizer.
        """
        text_parts = [self.current_instance["init"], self.current_instance["goal"]] + state.action_history
        return " ".join(text_parts).replace('\n', ' ')


# ==========================================
# 2. NEURAL NETWORK ARCHITECTURE
# ==========================================
class ThoughtHeurModel(nn.Module):
    """
    Predicts the Cost-to-Go (number of remaining thoughts to reach the goal).
    Powered by a frozen 7B LLM and trainable LoRA adapters!
    """
    def __init__(self, base_llm, tokenizer, max_len=192): # Capped to 192 from 256 to save VRAM
        super(ThoughtHeurModel, self).__init__()
        self.base_llm = base_llm
        self.tokenizer = tokenizer
        self.max_len = max_len
        
        # We define a single linear projection Value Head going from Llama-2's hidden dimension 4096 -> 1
        # This will be trained alongside the LoRA adapters!
        self.value_head = nn.Linear(4096, 1)

    def forward(self, thoughts_batch: list[str]):
        # 1. Tokenize the batch of text strings
        inputs = self.tokenizer(thoughts_batch, padding=True, truncation=True, 
                                max_length=self.max_len, return_tensors="pt").to(self.base_llm.device)
        
        # 2. Pass through the 7B LLM (with LoRA attached) to get the hidden state
        # We request output_hidden_states to retrieve the feature vectors
        outputs = self.base_llm(**inputs, output_hidden_states=True)
        
        # 3. Extract the last hidden state of the final token for each sequence in the batch
        # shape: [Batch_size, Seq_length, 4096]
        last_hidden_state = outputs.hidden_states[-1] 
        
        # Gather based on attention mask to find the final non-padding token
        seq_lengths = inputs['attention_mask'].sum(dim=1) - 1
        batch_size = last_hidden_state.shape[0]
        
        # Shape: [Batch_size, 4096]
        final_token_embeddings = last_hidden_state[torch.arange(batch_size), seq_lengths]
        
        # 4. Push through the final linear regression head
        # Cast the float16/nf4 features from the base LLM back to the dtype (usually float32)
        # of our trained Value Head to prevent precision mismatch matrix errors.
        features = final_token_embeddings.to(self.value_head.weight.dtype)
        out = self.value_head(features)
        
        # Enforce mathematical rule: Distance to goal cannot be negative
        return torch.relu(out)


# ==========================================
# 3. TRAINING LOOP
# ==========================================
class HeuristicTrainer:
    def __init__(self, env: BWThoughtEnv, model: ThoughtHeurModel, lr=1e-3):
        self.env = env
        self.model = model
        
        self.optimizer = optim.Adam(model.parameters(), lr=lr)
        self.criterion = nn.MSELoss()
        
        # Memory bank mapping transitions (State, is_solved, neighbors)
        self.replay_buffer = deque(maxlen=50000) 
        self.train_steps = 0

    def add_to_buffer(self, state: BWState):
        is_solved = self.env.is_goal(state)
        # ⚠️ Generation must ALWAYS use the base-model (no adapters)
        with self.base_llm.disable_adapter():
            neighbors = self.env.expand(state)
            
        # We only save to memory if there are actually neighbors available
        if neighbors or is_solved: 
            self.replay_buffer.append((state, is_solved, neighbors))


    def train_step(self, batch_size=32):
        if len(self.replay_buffer) < batch_size:
            return None
            
        # Sample mini-batch randomly
        batch = random.sample(self.replay_buffer, batch_size)
        states, is_solved_list, neighbors_batch = zip(*batch)
        
        inputs_text = [self.env.state_to_text(s) for s in states]
        targets = []
        
        with torch.no_grad():
            # Vectorized Target Calculation: Collate ALL neighbors from the entire batch!
            # This turns 64+ forward passes into exactly 1.
            all_neighbor_texts = []
            neighbor_indices = [] # Map which neighbor belongs to which batch item
            
            for i, state in enumerate(states):
                if not is_solved_list[i] and not self.env.is_terminal(state):
                    n_states = [n[0] for n in neighbors_batch[i]]
                    if n_states:
                        all_neighbor_texts.extend([self.env.state_to_text(ns) for ns in n_states])
                        neighbor_indices.append((i, len(n_states)))

            # Perform exactly ONE vectorized forward pass for all candidates
            all_n_values = []
            if all_neighbor_texts:
                self.model.eval()
                # Run batch inference
                all_n_values = self.model(all_neighbor_texts).squeeze(-1).tolist()
                if isinstance(all_n_values, float): all_n_values = [all_n_values]

            # Re-map results back to targets
            val_ptr = 0
            for i, state in enumerate(states):
                if is_solved_list[i]:
                    targets.append(0.0)
                elif self.env.is_terminal(state):
                    targets.append(10.0)
                else:
                    # Find candidates for this specific batch item
                    n_count = 0
                    for (idx, count) in neighbor_indices:
                        if idx == i:
                            n_count = count
                            break
                    
                    if n_count == 0:
                        targets.append(10.0)
                        continue
                        
                    curr_n_values = all_n_values[val_ptr : val_ptr + n_count]
                    n_costs = [n[1] for n in neighbors_batch[i]]
                    
                    target_val = min([c + nv for c, nv in zip(n_costs, curr_n_values)])
                    targets.append(target_val)
                    val_ptr += n_count
                    
        targets_tensor = torch.tensor(targets).unsqueeze(1).float().to(self.model.base_llm.device)
        
        # Forward and MSE Backprop
        self.model.train()
        # Ensure LoRA adapters are trainable in the base model
        self.model.base_llm.train()
        
        self.optimizer.zero_grad()
        predictions = self.model(inputs_text)
        loss = self.criterion(predictions, targets_tensor)
        loss.backward()
        
        # GRADIENT CLIPPING: Prevent weight explosion from unstable targets
        torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)
        
        self.optimizer.step()
        
        self.train_steps += 1
        return loss.item()


# ==========================================
# MAIN EXECUTION ROUTINE
# ==========================================
def main(
    base_lm: str = 'openai',
    model_dir: str = '',
    prompt_path: str = 'examples/CoT/blocksworld/prompts/pool_prompt_v1.json',
    data_path: str = 'examples/CoT/blocksworld/data/split_v1/split_v1_step_2_data.json',
    config_file: str = 'examples/CoT/blocksworld/data/bw_config.yaml',
    domain_file: str = 'examples/CoT/blocksworld/data/generated_domain.pddl',
    output_dir: str = 'logs/train_v_heur',
    batch_size: int = 16,
    n_candidate: int = 4,                   
    max_episodes: int = 20,                
    use_cache: bool = True,                 
    max_steps: int = 6,
    temperature: float = 0.8
):
    # ---------------------------------------------
    # SETUP LOGGING AND DIRS
    # ---------------------------------------------
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(output_dir, timestamp)
    os.makedirs(run_dir, exist_ok=True)
    
    print(f"Setting up training environment... Results will be saved to: {run_dir}")

    # ---------------------------------------------
    # LOAD PROMPT DICT
    # ---------------------------------------------
    with open(prompt_path) as f:
        prompt = json.load(f)

    # ---------------------------------------------
    # INITIALIZE LLM
    # ---------------------------------------------
    if base_lm == 'openai':
        from reasoners.lm import OpenAIModel
        # To match the logic in tot_inference.py
        model = OpenAIModel(model='gpt-3.5-turbo', temperature=temperature, max_tokens=2048)
    elif base_lm == 'exllama':
        from reasoners.lm import ExLlamaModel
        device = torch.device("cuda:0")
        model = ExLlamaModel(model_dir, lora_dir=None, device=device, 
                                max_batch_size=n_candidate, max_new_tokens=200, 
                                max_seq_length=2048, log_output=False)
        
        # ExLlamaModel.__init__ aggressively calls torch.set_grad_enabled(False) globally!
        # We must turn it back on so our ThoughtHeurModel can compute gradients.
        torch.set_grad_enabled(True)
    elif base_lm != "hf":
        raise NotImplementedError(f"Model {base_lm} not fully integrated into train_v_heur script yet.")

    # ---------------------------------------------
    # SETUP ToT BLOCKSWORLD INFRASTRUCTURE
    # ---------------------------------------------
    # Auto-detect PDDL VAL path if not set by the user's environment
    if "VAL" not in os.environ:
        val_path = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../../LLMs-Planning/planner_tools/VAL'))
        if os.path.exists(val_path):
            os.environ["VAL"] = val_path
        else:
            print(f"WARNING: The VAL environment variable is missing and could not be found at {val_path}.")
            
    if base_lm == "hf":
        from reasoners.lm.hf_model import HFModel
        
        # Monkey-patch legacy PyTorch versions (< 1.13) to support modern transformers auto-quantization
        # to guarantee `bitsandbytes` can inject its 4-bit Linear layers properly!
        if not hasattr(torch.nn.Module, "set_submodule"):
            def _set_submodule(self, target: str, module: torch.nn.Module) -> None:
                atoms = target.split(".")
                name = atoms.pop(-1)
                mod = self
                for item in atoms:
                    mod = getattr(mod, item)
                setattr(mod, name, module)
            torch.nn.Module.set_submodule = _set_submodule
        
        print(f"Loading {model_dir} in 4-bit NF4 for PEFT LoRA training (Takes ~4.5GB VRAM)...")
        # Load HuggingFace Model using 4-bit config via `quantized=nf4` built-into HFModel wrappers
        hf_wrapper = HFModel(model_dir, model_dir, device="cuda:0", 
                            max_batch_size=n_candidate, max_new_tokens=200, 
                            quantized="nf4")
        
        # Extract the underlying AutoModelForCausalLM
        base_llm = hf_wrapper.model
        tokenizer = hf_wrapper.tokenizer
        
        # Ensure tokenizer padding is set correctly for sequence batching
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
        
        print("Injecting LoRA Training Adapters using PEFT...")
        # Wrap the LLM with LoRA Adapters
        lora_config = LoraConfig(
            r=8,
            lora_alpha=16,
            target_modules=["q_proj", "v_proj"],
            lora_dropout=0.05,
            bias="none",
            task_type=TaskType.CAUSAL_LM
        )
        peft_model = get_peft_model(base_llm, lora_config)
        peft_model.print_trainable_parameters()
        
        # Hook the modified HuggingFace wrapper back into the ToT environment blocks
        # (This will be used for `.generate()` in the exploration phase)
        hf_wrapper.model = peft_model
        model = hf_wrapper
    else:
        raise NotImplementedError("Only `--base_lm hf` is supported for LoRA heuristic training right now! Please use it.")
        
    world_model = BlocksWorldModel(base_model=model, prompt=prompt, max_steps=max_steps)
    config = BWConfig(base_model=model, prompt=prompt, temperature=temperature, n_candidate=n_candidate)
    
    # We use DFS extractor here purely to satisfy the Evaluator object, but we overwrite output dynamically in is_goal anyway
    from examples.ToT.blocksworld.tot_inference import dfs_bw_extractor 
    evaluator = BWEvaluator(config_file=config_file, domain_file=domain_file, data_path=data_path, 
                            init_prompt=prompt, output_extractor=dfs_bw_extractor)

    # ---------------------------------------------
    # 80/20 DATASET SPLIT
    # ---------------------------------------------
    full_dataset = evaluator.full_dataset
    random.shuffle(full_dataset)
    split_idx = int(0.8 * len(full_dataset))
    train_data = full_dataset[:split_idx]
    test_data = full_dataset[split_idx:]
    
    # Save the splits so they can be reproduced!
    split_save_path = os.path.join(run_dir, "train_test_split.json")
    with open(split_save_path, "w") as f:
        json.dump({"train": train_data, "test": test_data}, f, indent=2)
    print(f"Loaded {len(train_data)} Train instances and {len(test_data)} Test instances.")

    # ---------------------------------------------
    # INITIALIZE RL ENVIRONMENT AND HEUR TRAINER
    # ---------------------------------------------
    env = BWThoughtEnv(world_model, config, evaluator, use_cache=use_cache)
    
    # Pre-build our environment vocabulary from all problems in the train test!
    # Because our network needs a fixed vocabulary at start, we inject all init/goal strings.
    for prob in train_data + test_data:
        env._update_vocab(prob["init"])
        env._update_vocab(prob["goal"])

    # Allocate Neural Net wrapped around the LoRA LLM
    heur_model = ThoughtHeurModel(base_llm=peft_model, tokenizer=tokenizer, max_len=256)
    heur_model.to(peft_model.device)
    
    trainer = HeuristicTrainer(env, heur_model)
    trainer.base_llm = peft_model # Pass reference to trainer for mode switching

    print("Beginning RL Epsilon-Greedy Random Walk...")
    
    # ---------------------------------------------
    # TRAINING LOOP
    # ---------------------------------------------
    for ep in range(max_episodes):
        # 1. Epsilon decay (more random at start, greedier at end)
        epsilon = max(0.1, 1.0 - (ep / (max_episodes * 0.5)))
        
        # 2. Pick a random problem instance to practice solving
        instance = random.choice(train_data)
        state = env.reset(instance)
        
        while True:
            # Replay buffer observation happens BEFORE taking an action
            trainer.add_to_buffer(state)
            
            if env.is_terminal(state):
                break
                
            # EXPLORATION: Explore a random LLM thought
            if random.random() < epsilon:
                # We temporarily disable the LoRA adapters so the LLM physically generated its base pre-trained thoughts!
                with trainer.base_llm.disable_adapter():
                    actions = env.get_actions_cached(state)
                if not actions:
                    break
                # choose random thought!
                action = random.choice(actions) 
                
            # EXPLOITATION: Ask heuristic which LLM thought yields the lowest remaining distance
            else:
                # IMPORTANT: Thoughts are ALWAYS generated by the base-model (no adapters)
                with trainer.base_llm.disable_adapter():
                    neighbors = env.expand(state)
                    
                n_states = [n[0] for n in neighbors]
                
                # If no thoughts available, we terminate the walk
                if len(n_states) == 0:
                    break
                
                # Format thoughts for Neural Network Evaluation
                n_texts = [env.state_to_text(ns) for ns in n_states]
                
                with torch.no_grad():
                    # Evaluate using the LoRA Network! (Enabled by default)
                    trainer.model.eval()
                    n_values = trainer.model(n_texts).squeeze(-1).tolist()
                    if isinstance(n_values, float): n_values = [n_values]
                
                # Pick thought with MINIMUM predicted cost
                best_idx = n_values.index(min(n_values))
                # Expand neighbor 0 element is state, from that we extract the *last action* to execute
                action = n_states[best_idx].action_history[-1]  
            
            # Formally take the step
            state, _ = env.world_model.step(state, action)

        # Step the gradients!
        loss = trainer.train_step(batch_size=batch_size)
        
        if ep % 2 == 0:
            print(f"Episode {ep:03d} | Loss: {loss if loss else 0.0:.4f} | Epsilon: {epsilon:.2f} | Local Vocab: {len(env.word2idx)} words")

        # PERIODIC MEMORY CLEANUP HOOK
        # Every 10 episodes, flush the CUDA cache and clean up fragmented tensors
        if ep % 10 == 0:
            import gc
            gc.collect()
            torch.cuda.empty_cache()

    print(f"\nTraining Complete! Saving final Model Weights to {run_dir}/heur_model.pth")
    torch.save(heur_model.state_dict(), os.path.join(run_dir, "heur_model.pth"))
    
    # Save the dictionary so future usages know how to map words -> IDs
    with open(os.path.join(run_dir, "vocab.json"), "w") as f:
        json.dump(env.word2idx, f, indent=2)
        

if __name__ == '__main__':
    fire.Fire(main)
