import os
import sys
import copy
import json
import random
import datetime
import time
from collections import deque
import logging
import contextlib

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import fire
from peft import get_peft_model, LoraConfig, TaskType

# Ensure we can import from the main project root
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from examples.ToT.blocksworld.tot_inference import BWConfig, BlocksWorldModel, BWState
from reasoners.benchmark.blocksworld import BWEvaluator
import reasoners.benchmark.bw_utils as bw_utils


# ==========================================
# 1. ENVIRONMENT WRAPPER
# ==========================================
class BWThoughtEnv:
    """
    Wraps the ToT BlocksWorld components (world_model, config, evaluator) into a standard 
    RL-style environment. Instead of tokens, a single "step" corresponds to a full text
    "thought" (an action generated by the LLM).
    """
    def __init__(self, world_model: BlocksWorldModel, config: BWConfig, evaluator: BWEvaluator, use_cache: bool = True):
        self.world_model = world_model
        self.config = config
        self.evaluator = evaluator
        
        # --- Caching System ---
        self.use_cache = use_cache
        # thought_cache maps a unique state signature to a list of possible thought strings proposed by the LLM
        self.thought_cache = {} 
        
        self.current_instance = None # Holds the active training problem
        self.current_prompt = None

    def reset(self, instance: dict):
        """Resets the environment to a specific BlocksWorld training problem."""
        self.current_instance = instance
        self.thought_cache = {} # CLEAR CACHE FOR NEW PROBLEM!!
        
        # 1. Ask the evaluator to randomly sample few-shot examples and build the complex prompt template
        self.current_prompt = self.evaluator.sample_prompt(shuffle_prompt=True, num_shot=4)
        
        # 2. Bind the active problem and the prompt framework to the action-generator (config)
        self.config.update_example(instance, prompt=self.current_prompt)
        
        # 3. Return the starting state (Step 0, clean action history)
        return self.world_model.init_state()

    def get_actions_cached(self, state: BWState):
        """Retrieves proposed thoughts from the LLM, securely checking the local Cache first."""
        if not self.use_cache:
            return self.config.get_actions(state)
            
        # The key is a string representation of the steps taken so far
        state_key = str(state.action_history)
        
        if state_key not in self.thought_cache:
            # Query the LLM (Very Expensive operation)
            actions = self.config.get_actions(state)
            self.thought_cache[state_key] = actions
                
        return self.thought_cache[state_key]

    def simulate_world(self, action_history, instance=None):
        """Helper to simulate the block world state from a list of NL actions.
        Strictly enforces Blocksworld physics preconditions - invalid LLM actions are silently skipped."""
        target_instance = instance if instance else self.current_instance
        if not target_instance:
            return {}, None
            
        init_str = target_instance["init"].lower()
        import re
        blocks = list(set(re.findall(r'the (\w+) block', init_str)))
        world = {}
        held = None

        for block in blocks:
            if f"the {block} block is on top of" in init_str:
                m = re.search(rf"the {block} block is on top of the (\w+) block", init_str)
                if m: world[block] = m.group(1)
            else:
                world[block] = "table"

        for action in action_history:
            action = action.lower().strip()
            # A block is clear if no other block in the world is sitting on top of it
            clear = {b for b in world if not any(world.get(o) == b for o in world)}

            if "pick up the" in action:
                m = re.search(r"pick up the (\w+) block", action)
                if m:
                    block = m.group(1)
                    # Preconditions: hand empty, block on table, block is clear
                    if held is None and world.get(block) == "table" and block in clear:
                        world[block] = "hand"
                        held = block
            elif "put down the" in action:
                m = re.search(r"put down the (\w+) block", action)
                if m:
                    block = m.group(1)
                    # Preconditions: hand is holding this block
                    if held == block:
                        world[block] = "table"
                        held = None
            elif "unstack the" in action:
                m = re.search(r"unstack the (\w+) block from on top of the (\w+) block", action)
                if m:
                    block, from_block = m.group(1), m.group(2)
                    # Preconditions: hand empty, block is on from_block, block is clear
                    if held is None and world.get(block) == from_block and block in clear:
                        world[block] = "hand"
                        held = block
            elif "stack the" in action:
                m = re.search(r"stack the (\w+) block on top of the (\w+) block", action)
                if m:
                    block, onto = m.group(1), m.group(2)
                    # Preconditions: hand holding block, target block is clear
                    if held == block and onto in clear:
                        world[block] = onto
                        held = None
        return world, held

    def is_terminal(self, state: BWState, instance=None) -> bool:
        """A state is a dead-end if we reached the step limit or already solved the problem."""
        return self.world_model.is_terminal(state) or self.is_goal(state, instance)

    def expand(self, state: BWState) -> list:
        """Returns a list of tuples (next_state, step_cost) for all possible thoughts from the LLM."""
        actions = self.get_actions_cached(state)
        results = []
        for action in actions:
            next_state, _ = self.world_model.step(state, action)
            results.append((next_state, 1.0)) # Every thought executed costs 1 step
        return results

    def is_goal(self, state: BWState, instance=None) -> bool:
        """Pure Python Blocksworld goal checker.
        
        Checks ALL goal condition types:
          - 'the X block is on top of the Y block'
          - 'the X block is on the table'
          - 'the hand is empty'
        A state is a goal ONLY when every condition is satisfied.
        """
        target_instance = instance if instance else self.current_instance
        if not target_instance or len(state.action_history) == 0:
            return False
            
        world, held = self.simulate_world(state.action_history, instance)
        goal_str = target_instance["goal"].lower()
        import re

        found_any_condition = False

        # Condition type 1: "the X block is on top of the Y block"
        on_top_conditions = re.findall(r'the (\w+) block is on top of the (\w+) block', goal_str)
        for upper, lower in on_top_conditions:
            found_any_condition = True
            if world.get(upper) != lower:
                return False

        # Condition type 2: "the X block is on the table"
        on_table_conditions = re.findall(r'the (\w+) block is on the table', goal_str)
        for block in on_table_conditions:
            found_any_condition = True
            if world.get(block) != "table":
                return False

        # Condition type 3: "the hand is empty"
        if "the hand is empty" in goal_str:
            found_any_condition = True
            if held is not None:
                return False

        # Safety: if no recognized conditions were found, do not falsely claim goal
        if not found_any_condition:
            return False

        return True

    def state_to_text(self, state: BWState, instance=None) -> str:
        """Converts current world state into a clean physical description."""
        world, held = self.simulate_world(state.action_history, instance)
        
        # Build a flat string of positions: "the red block is on the table, the blue block is on red..."
        parts = []
        for b, pos in world.items():
            if pos == "table": parts.append(f"the {b} block is on the table")
            elif pos == "hand": parts.append(f"the {b} block is in the hand")
            else: parts.append(f"the {b} block is on top of the {pos} block")
            
        current_state_str = ", ".join(parts)
        target_instance = instance if instance else self.current_instance
        # FLIPPED: Put the Goal at the END so its information is closest to the last-token embedding
        text = f"Current State: {current_state_str} | Goal: {target_instance['goal']}"
        return text

# ==========================================
# 2. NEURAL NETWORK ARCHITECTURE
# ==========================================
class ThoughtHeurModel(nn.Module):
    """
    Predicts the Cost-to-Go (number of remaining thoughts to reach the goal).
    Powered by a frozen 7B LLM and trainable LoRA adapters!
    """
    def __init__(self, base_llm, tokenizer, max_len=192): # Capped to 192 from 256 to save VRAM
        super(ThoughtHeurModel, self).__init__()
        self.base_llm = base_llm
        self.tokenizer = tokenizer
        self.max_len = max_len
        
        # We define a single linear projection Value Head going from Llama-2's hidden dimension 4096 -> 1
        self.value_head = nn.Linear(4096, 1)
        
        # STABILITY INIT: Initialize with bias 2.0 (down from 5.0) 
        # to make it easier to reach the 0.0 goal state targets.
        nn.init.xavier_uniform_(self.value_head.weight)
        nn.init.constant_(self.value_head.bias, 2.0)

    def forward(self, thoughts_batch: list[str]):
        # Enforce right-padding so the final token aligns correctly with the attention_mask computation
        self.tokenizer.padding_side = 'right'

        # 1. Tokenize the batch of text strings
        inputs = self.tokenizer(thoughts_batch, padding=True, truncation=True, 
                                max_length=self.max_len, return_tensors="pt").to(self.base_llm.device)
        
        # 2. Pass through the 7B LLM (with LoRA attached) to get the hidden state
        # We request output_hidden_states to retrieve the feature vectors
        outputs = self.base_llm(**inputs, output_hidden_states=True)
        
        # 3. Extract the last hidden state of the final token for each sequence in the batch
        # shape: [Batch_size, Sequence_Length, Features (4096)]
        final_layer_features = outputs.hidden_states[-1] 
        
        # Gather based on attention mask to find the final non-padding token
        seq_lengths = inputs['attention_mask'].sum(dim=1) - 1
        batch_size = final_layer_features.shape[0]
        
        # Shape: [Batch_size, 4096]
        final_token_embeddings = final_layer_features[torch.arange(batch_size), seq_lengths]
        
        # 4. Push through the final linear regression head
        # Cast the float16/nf4 features from the base LLM back to the dtype (usually float32)
        # of our trained Value Head to prevent precision mismatch matrix errors.
        features = final_token_embeddings.to(self.value_head.weight.dtype)
        out = self.value_head(features)
        
        # Enforce mathematical rule: Distance to goal cannot be negative
        # return F.relu(out)
        return out


# ==========================================
# 3. TRAINING LOOP
# ==========================================
class HeuristicTrainer:
    def __init__(self, env: BWThoughtEnv, model: ThoughtHeurModel, lr=1e-4): 
        self.env = env
        self.model = model
        
        # PARAM-SPECIFIC LEARNING RATES:
        # We give the Value Head a MUCH higher LR than the LoRA adapters
        # so it can map features to distances aggressively.
        self.optimizer = optim.Adam([
            {'params': model.value_head.parameters(), 'lr': lr}, # 1e-4
            {'params': model.base_llm.parameters(), 'lr': lr * 0.1} # 1e-5 (LoRA)
        ], weight_decay=0.001)
        
        self.criterion = nn.SmoothL1Loss(beta=2.0) # Tighter quadratic window (error=2.0)
        
        # Memory bank mapping transitions (State, is_solved, neighbors)
        # We split the buffer to ensure we always have "Grounding" (Goal) examples in every batch
        self.buffer_pos = deque(maxlen=20000) # Goals or Goal-Adjacent
        self.buffer_neg = deque(maxlen=30000) # Everything else
        self.train_steps = 0

    def add_to_buffer(self, state: BWState):
        is_solved = self.env.is_goal(state)
        # ⚠️ Generation must ALWAYS use the base-model (no adapters)
        with self.base_llm.disable_adapter():
            neighbors = self.env.expand(state)
            
        # EXPLICITLY ADD ANY DISCOVERED GOAL STATES TO POSITIVE BUFFER
        # This guarantees the model sees `0.0` examples!
        # ATTACH INSTANCE to prevent cross-pollution during evaluation!
        for n_state, _ in neighbors:
            if self.env.is_goal(n_state):
                self.buffer_pos.append((n_state, True, [], self.env.current_instance))

        any_neighbor_is_goal = any([self.env.is_goal(n[0]) for n in neighbors])
        
        # We only save to memory if there are actually neighbors available
        if neighbors or is_solved: 
            entry = (state, is_solved, neighbors, self.env.current_instance)
            if is_solved or any_neighbor_is_goal:
                self.buffer_pos.append(entry)
            else:
                self.buffer_neg.append(entry)


    def train_step(self, batch_size=32):
        if (len(self.buffer_pos) + len(self.buffer_neg)) < batch_size:
            return None
            
        # PRIORITY SAMPLING: 50% from Positive Buffer, 50% from Negative
        # We need to "scream" the goal signal (50% of batch) to drown out the garbage states.
        n_pos = min(len(self.buffer_pos), batch_size // 2)
        n_neg = batch_size - n_pos
        
        # Safely pull overflow from pos_buffer if neg_buffer hasn't populated entirely yet
        if n_neg > len(self.buffer_neg):
            n_neg = len(self.buffer_neg)
            n_pos = batch_size - n_neg
        
        batch = random.sample(self.buffer_pos, n_pos) + random.sample(self.buffer_neg, n_neg)
        random.shuffle(batch)
        
        states, is_solved_list, neighbors_batch, instances_batch = zip(*batch)
        
        inputs_text = [self.env.state_to_text(s, inst) for s, inst in zip(states, instances_batch)]
        targets = []
        
        with torch.no_grad():
            # Vectorized Target Calculation: Collate ALL neighbors from the entire batch!
            # This turns 64+ forward passes into exactly 1.
            all_neighbor_texts = []
            neighbor_indices = [] # Map which neighbor belongs to which batch item
            
            for i, state in enumerate(states):
                if not is_solved_list[i]:
                    neighbor_states = [neighbor[0] for neighbor in neighbors_batch[i]]
                    if neighbor_states:
                        all_neighbor_texts.extend([self.env.state_to_text(ns, instances_batch[i]) for ns in neighbor_states])
                        neighbor_indices.append((i, len(neighbor_states)))

            # Perform exactly ONE vectorized forward pass for all candidates
            all_neighbor_values = []
            if all_neighbor_texts:
                self.model.eval()
                # Run batch inference
                all_neighbor_values = self.model(all_neighbor_texts).squeeze(-1).tolist()
                if isinstance(all_neighbor_values, float):
                    all_neighbor_values = [all_neighbor_values]

            # Re-map results back to targets
            val_ptr = 0
            for i, state in enumerate(states):
                if is_solved_list[i]:
                    targets.append(0.0)
                else:
                    # Find candidates for this specific batch item
                    n_count = 0
                    for (idx, count) in neighbor_indices:
                        if idx == i:
                            n_count = count
                            break
                    
                    if n_count == 0:
                        # True dead end (LLM proposed zero actions), give massive penalty
                        targets.append(50.0)
                        continue
                        
                    curr_n_values = all_neighbor_values[val_ptr : val_ptr + n_count]
                    n_costs = [n[1] for n in neighbors_batch[i]]
                    # Check if any neighbor is physically the goal
                    n_is_goal = [self.env.is_goal(n[0], instances_batch[i]) for n in neighbors_batch[i]]
                    
                    # GROUNDING: If any neighbor is the goal, the target is exactly the step cost (1.0)
                    if any(n_is_goal):
                        target_val = 1.0
                    else:
                        # ADI CORE: target = min(neighbor_cost + predicted_neighbor_value)
                        target_val = min([c + nv for c, nv in zip(n_costs, curr_n_values)])
                        
                    targets.append(target_val)
                    val_ptr += n_count
                    
        targets_tensor = torch.tensor(targets).unsqueeze(1).float().to(self.model.base_llm.device)
        
        # Forward and MSE Backprop
        self.model.train()
        # Ensure LoRA adapters are trainable in the base model
        self.model.base_llm.train()
        
        self.optimizer.zero_grad()
        predictions = self.model(inputs_text)
        loss = self.criterion(predictions, targets_tensor)
        loss.backward()
        
        # GRADIENT CLIPPING: Prevent weight explosion from unstable targets
        # clip_grad_norm_ mathematically returns the true unclipped gradient norm!
        grad_norm = torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0).item()
        
        self.optimizer.step()
        
        # MONITORING: Calculate Value Variance to see if the model is "dead"
        with torch.no_grad():
            v_std = predictions.std().item()
            v_mean = predictions.mean().item()
            v_min = predictions.min().item()
            v_max = predictions.max().item()
        
        self.train_steps += 1
        return loss.item(), (v_mean, v_std, v_min, v_max, grad_norm)


# ==========================================
# MAIN EXECUTION ROUTINE
# ==========================================
def main(
    base_lm: str = 'openai',
    model_dir: str = '',
    prompt_path: str = 'examples/CoT/blocksworld/prompts/pool_prompt_v1.json',
    data_path: str = 'examples/CoT/blocksworld/data/split_v1/split_v1_step_2_data.json',
    config_file: str = 'examples/CoT/blocksworld/data/bw_config.yaml',
    domain_file: str = 'examples/CoT/blocksworld/data/generated_domain.pddl',
    output_dir: str = 'logs/train_v_heur',
    batch_size: int = 16,
    n_candidate: int = 4,                   
    max_episodes: int = 20,                
    use_cache: bool = True,                 
    max_steps: int = 10,
    temperature: float = 0.8,
    save_model_every: int = None
):
    # ---------------------------------------------
    # SETUP LOGGING AND DIRS
    # ---------------------------------------------
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(output_dir, timestamp)
    os.makedirs(run_dir, exist_ok=True)
    
    print(f"Setting up training environment... Results will be saved to: {run_dir}")

    # ---------------------------------------------
    # LOAD PROMPT DICT
    # ---------------------------------------------
    with open(prompt_path) as f:
        prompt = json.load(f)

    # ---------------------------------------------
    # INITIALIZE LLM
    # ---------------------------------------------
    if base_lm == 'openai':
        from reasoners.lm import OpenAIModel
        # To match the logic in tot_inference.py
        model = OpenAIModel(model='gpt-3.5-turbo', temperature=temperature, max_tokens=2048)
    elif base_lm == 'exllama':
        from reasoners.lm import ExLlamaModel
        device = torch.device("cuda:0")
        model = ExLlamaModel(model_dir, lora_dir=None, device=device, 
                                max_batch_size=n_candidate, max_new_tokens=200, 
                                max_seq_length=2048, log_output=False)
        
        # ExLlamaModel.__init__ aggressively calls torch.set_grad_enabled(False) globally!
        # We must turn it back on so our ThoughtHeurModel can compute gradients.
        torch.set_grad_enabled(True)
    elif base_lm != "hf":
        raise NotImplementedError(f"Model {base_lm} not fully integrated into train_v_heur script yet.")

    # ---------------------------------------------
    # SETUP ToT BLOCKSWORLD INFRASTRUCTURE
    # ---------------------------------------------
    # Auto-detect PDDL VAL path if not set by the user's environment
    if "VAL" not in os.environ:
        val_path = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../../LLMs-Planning/planner_tools/VAL'))
        if os.path.exists(val_path):
            os.environ["VAL"] = val_path
        else:
            print(f"WARNING: The VAL environment variable is missing and could not be found at {val_path}.")
            
    if base_lm == "hf":
        from reasoners.lm.hf_model import HFModel
        
        # Monkey-patch legacy PyTorch versions (< 1.13) to support modern transformers auto-quantization
        # to guarantee `bitsandbytes` can inject its 4-bit Linear layers properly!
        if not hasattr(torch.nn.Module, "set_submodule"):
            def _set_submodule(self, target: str, module: torch.nn.Module) -> None:
                atoms = target.split(".")
                name = atoms.pop(-1)
                mod = self
                for item in atoms:
                    mod = getattr(mod, item)
                setattr(mod, name, module)
            torch.nn.Module.set_submodule = _set_submodule
        
        print(f"Loading {model_dir} in 4-bit NF4 for PEFT LoRA training (Takes ~4.5GB VRAM)...")
        # Load HuggingFace Model using 4-bit config via `quantized=nf4` built-into HFModel wrappers
        hf_wrapper = HFModel(model_dir, model_dir, device="cuda:0", 
                            max_batch_size=n_candidate, max_new_tokens=200, 
                            quantized="nf4")
        
        # Extract the underlying AutoModelForCausalLM
        base_llm = hf_wrapper.model
        tokenizer = hf_wrapper.tokenizer
        
        # Ensure tokenizer padding is set correctly for sequence batching
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
        
        print("Injecting LoRA Training Adapters using PEFT...")
        # Wrap the LLM with LoRA Adapters
        lora_config = LoraConfig(
            r=8,
            lora_alpha=16,
            target_modules=["q_proj", "v_proj"],
            lora_dropout=0.05,
            bias="none",
            task_type=TaskType.CAUSAL_LM
        )
        peft_model = get_peft_model(base_llm, lora_config)
        peft_model.print_trainable_parameters()
        
        # Hook the modified HuggingFace wrapper back into the ToT environment blocks
        # (This will be used for `.generate()` in the exploration phase)
        hf_wrapper.model = peft_model
        model = hf_wrapper
    else:
        raise NotImplementedError("Only `--base_lm hf` is supported for LoRA heuristic training right now! Please use it.")
        
    world_model = BlocksWorldModel(base_model=model, prompt=prompt, max_steps=max_steps)
    config = BWConfig(base_model=model, prompt=prompt, temperature=temperature, n_candidate=n_candidate)
    
    # We use DFS extractor here purely to satisfy the Evaluator object, but we overwrite output dynamically in is_goal anyway
    from examples.ToT.blocksworld.tot_inference import dfs_bw_extractor 
    evaluator = BWEvaluator(config_file=config_file, domain_file=domain_file, data_path=data_path, 
                            init_prompt=prompt, output_extractor=dfs_bw_extractor)

    # ---------------------------------------------
    # 80/20 DATASET SPLIT
    # ---------------------------------------------
    full_dataset = evaluator.full_dataset
    random.shuffle(full_dataset)
    split_idx = int(0.8 * len(full_dataset))
    train_data = full_dataset[:split_idx]
    test_data = full_dataset[split_idx:]
    
    # Save the splits so they can be reproduced!
    split_save_path = os.path.join(run_dir, "train_test_split.json")
    with open(split_save_path, "w") as f:
        json.dump({"train": train_data, "test": test_data}, f, indent=2)
    print(f"Loaded {len(train_data)} Train instances and {len(test_data)} Test instances.")

    # ---------------------------------------------
    # INITIALIZE RL ENVIRONMENT AND HEUR TRAINER
    # ---------------------------------------------
    env = BWThoughtEnv(world_model, config, evaluator, use_cache=use_cache)

    # Allocate Neural Net wrapped around the LoRA LLM
    heur_model = ThoughtHeurModel(base_llm=peft_model, tokenizer=tokenizer, max_len=256)
    heur_model.to(peft_model.device)
    
    trainer = HeuristicTrainer(env, heur_model)
    trainer.base_llm = peft_model # Pass reference to trainer for mode switching

    print("Beginning RL Epsilon-Greedy Random Walk...")
    
    # ---------------------------------------------
    # TRAINING LOOP
    # ---------------------------------------------
    start_time = time.time()
    last_log_time = start_time
    
    history_loss = []
    history_heur_mean = []
    
    goals_reached = 0   # Counts goal reached in the last log window (2 episodes)
    for ep in range(max_episodes):
        # 1. Epsilon decay (more random at start, greedier at end)
        epsilon = max(0.1, 1.0 - (ep / (max_episodes * 0.5)))
        
        # 2. Pick a random problem instance to practice solving
        instance = random.choice(train_data)
        state = env.reset(instance)
        
        while True:
            # Replay buffer observation happens BEFORE taking an action
            trainer.add_to_buffer(state)
            
            if env.is_terminal(state):
                break
                
            # EXPLORATION: Explore a random LLM thought
            if random.random() < epsilon:
                # We temporarily disable the LoRA adapters so the LLM physically generated its base pre-trained thoughts!
                with trainer.base_llm.disable_adapter():
                    actions = env.get_actions_cached(state)
                if not actions:
                    break
                # choose random thought!
                action = random.choice(actions) 
                
            # EXPLOITATION: Ask heuristic which LLM thought yields the lowest remaining distance
            else:
                # IMPORTANT: Thoughts are ALWAYS generated by the base-model (no adapters)
                with trainer.base_llm.disable_adapter():
                    neighbors = env.expand(state)
                    
                n_states = [n[0] for n in neighbors]
                
                # If no thoughts available, we terminate the walk
                if len(n_states) == 0:
                    break
                
                # Format thoughts for Neural Network Evaluation
                n_texts = [env.state_to_text(ns) for ns in n_states]
                
                with torch.no_grad():
                    # Evaluate using the LoRA Network! (Enabled by default)
                    trainer.model.eval()
                    n_values = trainer.model(n_texts).squeeze(-1).tolist()
                    if isinstance(n_values, float): n_values = [n_values]
                
                # Pick thought with MINIMUM predicted cost
                best_idx = n_values.index(min(n_values))
                # Expand neighbor 0 element is state, from that we extract the *last action* to execute
                action = n_states[best_idx].action_history[-1]  
            
            # Formally take the step
            state, _ = env.world_model.step(state, action)

        # Track if this episode ended at the goal
        if env.is_goal(state):
            goals_reached += 1

        # Step the gradients!
        res = trainer.train_step(batch_size=batch_size)
        if res:
            loss, (v_mean, v_std, v_min, v_max, grad_norm) = res
        else:
            loss, v_mean, v_std, v_min, v_max, grad_norm = 0, 0, 0, 0, 0, 0
            
        history_loss.append(loss)
        history_heur_mean.append(v_mean)
        
        if ep % 2 == 0:
            current_time = time.time()
            elapsed_since_log = current_time - last_log_time
            total_elapsed = current_time - start_time
            
            avg_time_per_ep = total_elapsed / max(1, ep)
            est_remaining = avg_time_per_ep * (max_episodes - ep - 1)
            est_rem_str = str(datetime.timedelta(seconds=int(est_remaining)))
            
            print(f"Episode {ep:03d} | Loss: {loss:.3f} | Grad: {grad_norm:.2f} | Range: [{v_min:.1f}-{v_max:.1f}] | Std: {v_std:.2f} | Goals: {goals_reached}/2 | Time/2Ep: {elapsed_since_log:.1f}s | Est. Rem: {est_rem_str}")
            
            goals_reached = 0  # Reset window counter
            last_log_time = current_time

        if save_model_every is not None and ep > 0 and ep % save_model_every == 0:
            chkpt_dir = os.path.join(run_dir, "checkpoints")
            os.makedirs(chkpt_dir, exist_ok=True)
            chkpt_path = os.path.join(chkpt_dir, f"heur_model_ep{ep:05d}.pth")
            trainable_state_dict = {k: v for k, v in heur_model.state_dict().items() if "lora" in k or "value_head" in k}
            torch.save(trainable_state_dict, chkpt_path)
            print(f"  [>] Saved intermediate checkpoint to: {chkpt_path}")

    print(f"\nTraining Complete! Saving final Model Weights to {run_dir}/heur_model.pth")
    # ONLY save the Trainable parameters (LoRA adapters + Value Head) to save 4.5GB of disk space!
    trainable_state_dict = {k: v for k, v in heur_model.state_dict().items() if "lora" in k or "value_head" in k}
    torch.save(trainable_state_dict, os.path.join(run_dir, "heur_model.pth"))
    
    # ---------------------------------------------
    # SAVE TRAINING GRAPHS
    # ---------------------------------------------
    try:
        import matplotlib.pyplot as plt
        import numpy as np
        
        window = min(50, len(history_loss))
        if window > 1:
            smooth_loss = np.convolve(history_loss, np.ones(window)/window, mode='valid')
            smooth_heur = np.convolve(history_heur_mean, np.ones(window)/window, mode='valid')
            x_axis = range(window - 1, len(history_loss))
        else:
            smooth_loss = history_loss
            smooth_heur = history_heur_mean
            x_axis = range(len(history_loss))
        
        # 1. Loss Graph
        plt.figure(figsize=(10, 5))
        plt.plot(range(len(history_loss)), history_loss, alpha=0.3, label="Raw Batch Loss", color="blue")
        plt.plot(x_axis, smooth_loss, label=f"Smoothed Loss (Window={window})", color="blue", linewidth=2.0)
        plt.xlabel("Updates")
        plt.ylabel("Loss")
        plt.title("Neural Network Loss Over Time")
        plt.grid(True, linestyle="--", alpha=0.6)
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(run_dir, "plot_loss.png"))
        plt.close()
        
        # 2. Heuristics Average Graph
        plt.figure(figsize=(10, 5))
        plt.plot(range(len(history_heur_mean)), history_heur_mean, alpha=0.3, label="Raw Batch Mean", color="orange")
        plt.plot(x_axis, smooth_heur, label=f"Smoothed Mean (Window={window})", color="darkorange", linewidth=2.0)
        plt.xlabel("Updates")
        plt.ylabel("Mean Heuristic Validated Value")
        plt.title("Average Heuristic Prediction Over Time")
        plt.grid(True, linestyle="--", alpha=0.6)
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(run_dir, "plot_heur_mean.png"))
        plt.close()
        print("Successfully saved Loss and Heuristic graphs as PNGs.")
    except Exception as e:
        print(f"Could not save training graphs (matplotlib may not be installed): {e}")
        

if __name__ == '__main__':
    fire.Fire(main)
